export const GET_ARTIST = 'GET_ARTIST'
export const SEARCH_ARTIST = 'SEARCH_ARTIST'
export const LOADING = 'LOADING';
export const GET_ARTIST_PROFILE = 'GET_ARTIST_PROFILE'
export const GET_ARTIST_ALBUMS = 'GET_ARTIST_ALBUMS'
export const GET_ALBUM_TRACKS = 'GET_ALBUM_TRACKS'
export const GET_CURRENT_PLAYING = 'GET_CURRENT_PLAYING'
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN'
export const GET_SONG_URI = 'GET_SONG_URI'




